apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-management-system
  labels:
    app: school-management-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-management-system
  template:
    metadata:
      labels:
        app: school-management-system
    spec:
      containers:
      - name: school-management-system
        image: khaledelnabawy1/school_management_system:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: env-file
            mountPath: /var/www/html/.env
            subPath: .env
      volumes:
        - name: env-file
          configMap:
            name: school-env
---
apiVersion: v1
kind: Service
metadata:
  name: school-management-system-svc
spec:
  type: LoadBalancer
  selector:
    app: school-management-system
  ports:
    - port: 80
      targetPort: 80
